spring.application.name=pc1-dbp
spring.datasource.url=jdbc:postgresql://localhost:5432/pc1-dbp
spring.datasource.url=postgres.password=postgress.driver-class-home=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernatedialect.Postgresqldialect
jwt-secret=404
